services:
  ocis:
    container_name: ocis
    image: owncloud/ocis:latest
    restart: unless-stopped
    volumes:
      - ./ocis/config:/etc/ocis:Z
      - ./ocis/data:/var/lib/ocis:Z
      - ./ocis/logs:/logs:Z
      - ./certs:/certs:Z,ro
    ports:
      - 9200:9200/tcp
    env_file:
      - ocis.env
    user: "200004:200004"
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    entrypoint:
      - /bin/sh
    command: [ "-c", "exec ocis server" ]
#    command: [ "-c", "ocis init || true; exec ocis server" ]
