services:
  postgres:
    container_name: postgres
    image: ghcr.io/polarix-containers/postgres:18
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/18/docker:Z
      - ./postgres_dump:/dump:Z
    networks:
      - postgres
    env_file:
      - postgres.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
      interval: 15s
      timeout: 5s
    user: "200012:200012"
    read_only: true
    tmpfs:
      - /var/run/postgresql:size=50M,mode=0770,uid=200012,gid=200012,noexec,nosuid,nodev
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.5.1
    restart: unless-stopped
    volumes:
      - ./certs:/certs:Z
    ports:
      - 8443:8443/tcp
    networks:
      - keycloak
      - postgres
    env_file:
      - keycloak.env
    security_opt:
      - "no-new-privileges=true"
    cap_drop:
      - ALL
    command: start

networks:
  keycloak:
  postgres:
    internal: true
