role_assignment:
  driver: oidc
  oidc_role_mapper:
    role_claim: role
    role_mapping:
      - role_name: admin
        claim_value: admin
      - role_name: user
        claim_value: user

# Role IDs are hardcoded
# https://github.com/owncloud/ocis/blob/e3dae1b48a74ab0e6d4d61a3f2f0988dbe2c5957/services/settings/pkg/store/defaults/defaults.go#L9-L17
# We are giving both admin and user 20GB by default

role_quotas:
  71881883-1768-46bd-a24d-a356a2afdf7f: 20000000000
  d7beeea8-8ff4-406b-8fb6-ab2dd81e6b11: 20000000000