worker_replication_secret: REDACTED
update_user_directory_from_worker: no_load_balance_worker
notify_appservices_from_worker: no_load_balance_worker

redis:
  enabled: true
  host: 'valkey'

instance_map:
  main:
    host: 'synapse'
    port: 9093
  generic_worker-1:
    host: 'generic_worker-1'
    port: 9093
  generic_worker-2:
    host: 'generic_worker-2'
    port: 9093

stream_writers:
#  events:
#    - generic_worker-1
#    - generic_worker-2
  receipts:
    - generic_worker-1
    - generic_worker-2
  device_lists:
    - generic_worker-1
    - generic_worker-2