worker_replication_secret: REDACTED
update_user_directory_from_worker: no_load_balance_worker
notify_appservices_from_worker: no_load_balance_worker

redis:
  enabled: true
  host: 'valkey'

instance_map:
  main:
    host: 'synapse'
    port: 9093